<template>
  <table class="table is-border is-center is-middle">
    <thead>
      <tr>
        <th>診療時間</th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
        <th>日/祝</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>9:00～12:00</td>
        <td>○</td>
        <td>○</td>
        <td>○</td>
        <td></td>
        <td>○</td>
        <td>○</td>
        <td></td>
      </tr>
      <tr>
        <td>14:00～19:00</td>
        <td>○</td>
        <td>○</td>
        <td>○</td>
        <td></td>
        <td>○</td>
        <td>○</td>
        <td></td>
      </tr>
    </tbody>
  </table>
</template>
